language: python
python:
- 3.6
before_install:
- openssl aes-256-cbc -K $encrypted_189b02ce2608_key -iv $encrypted_189b02ce2608_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
install:
- pip install -r requirements.txt
before_script:
- cd instagram
script:
- python manage.py test
