# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 02:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_auto_20171019_0645'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
