# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 05:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_auto_20171114_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(blank=True, max_length=10, verbose_name='별명'),
        ),
    ]
