# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 07:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0006_auto_20171114_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='nickname',
        ),
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(default=20, verbose_name='나이'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='like_posts',
            field=models.ManyToManyField(blank=True, related_name='like_users', to='post.Post', verbose_name='좋아요 누른 포스트 목록'),
        ),
    ]
