# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 07:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0008_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='abc', max_length=10, verbose_name='별명'),
            preserve_default=False,
        ),
    ]
